project_id = "lzvvnmhbyyxsukywjhin"

[functions.process-standard]
verify_jwt = false

[functions.query]
verify_jwt = false

[functions.upload-standard]
verify_jwt = false

[functions.capstone]
verify_jwt = false
