project_id = "wyxeqkgpwkcckyntqcns"

[functions.process-standard]
verify_jwt = false

[functions.query]
verify_jwt = false

[functions.upload-standard]
verify_jwt = false

[functions.capstone]
verify_jwt = false

[functions.chunk-test]
verify_jwt = false

[functions.query-test]
verify_jwt = false
