// Shared chunk-build-and-persist step, used by both process-standard (first
// processing of a newly uploaded standard) and reprocess-standard (re-running
// chunking/tagging against an already-stored standard without a fresh
// upload). Kept separate from extraction.ts (pure, no Deno/network deps) and
// ocr.ts (PDF text extraction) since this piece talks to Supabase.
import {
  type Chunk,
  sortIntoSections,
  chunkSections,
  extractTableChunks,
  extractFigureChunks,
  buildDocumentMapChunk,
  stripRepeatedPageFurniture,
} from "./extraction.ts";

// deno-lint-ignore no-explicit-any
type SupabaseAdmin = any;

export interface ChunkAndPersistParams {
  standard_id: string;
  userId: string;
  organizationId: string | null;
  standardCode: string;
  version: string;
  pages: string[];
  tier: string;
  qualityScore: number;
  pipelineVersion: number;
  // clause_number ("TABLE 4.1" / "FIGURE 2.3") -> previously-described
  // content, for chunks whose vision transcription/description already ran
  // and should NOT be re-run just because clause chunking changed. Only
  // populated by reprocess-standard; process-standard's first-ever run of a
  // standard never has anything to carry forward.
  preserveDescribed?: Map<string, string>;
}

export interface ChunkAndPersistResult {
  totalChunks: number;
  tableChunkCount: number;
  figureChunkCount: number;
  isPartial: boolean;
}

const DB_BATCH_SIZE = 100;

export async function chunkAndPersist(
  supabaseAdmin: SupabaseAdmin,
  params: ChunkAndPersistParams,
): Promise<ChunkAndPersistResult> {
  const {
    standard_id, userId, organizationId, standardCode, version, pages,
    tier, qualityScore, pipelineVersion, preserveDescribed,
  } = params;

  // Figure/table detection needs the [PAGE N] markers to work out which page
  // each one is on. Per-page licence/header boilerplate is stripped here so
  // every downstream consumer — sectioning, clause chunks, table/figure
  // extraction — is furniture-free.
  const markedText = stripRepeatedPageFurniture(
    pages.map((p, i) => `[PAGE ${i + 1}]\n${p}`).join("\n"),
  );
  const sections = sortIntoSections(markedText);
  const clauseChunks = chunkSections(sections, standardCode, version);
  const tableChunks = extractTableChunks(markedText, standardCode, version);
  const figureChunks = extractFigureChunks(markedText, standardCode, version);
  // Free, auto-generated table of contents — see buildDocumentMapChunk
  const mapChunk = buildDocumentMapChunk(sections, standardCode, version);
  console.log(`[${standard_id}] Found ${tableChunks.length} table chunks, ${figureChunks.length} figure chunks${mapChunk ? ", + document map" : ""}`);

  // Merge and re-assign chunk_index globally (map first so it's always indexed)
  const allChunks: Chunk[] = [...(mapChunk ? [mapChunk] : []), ...clauseChunks, ...tableChunks, ...figureChunks].map((chunk, idx) => ({
    ...chunk,
    chunk_index: idx,
  }));
  const totalChunks = allChunks.length;
  console.log(`[${standard_id}] Chunking done: ${totalChunks} chunks`);

  const isPartial = tier === "free";

  // Delete stale chunks from previous extractions before inserting fresh ones
  const { error: deleteError } = await supabaseAdmin
    .from("standard_chunks")
    .delete()
    .eq("standard_id", standard_id);
  if (deleteError) console.error(`Failed to delete old chunks for ${standard_id}:`, deleteError);
  else console.log(`[${standard_id}] Deleted old chunks`);

  // Insert all chunks as text-only — embeddings are generated by embed-chunks
  // separately. A table/figure chunk whose clause_number matches an already-
  // described entry carries that content forward and is marked is_indexed so
  // describe-figures (which filters on is_indexed = false) skips it — no
  // re-run of vision transcription just because the surrounding clause text
  // changed. It still gets embedding = NULL like every other chunk here, so
  // embed-chunks re-embeds it (cheap) rather than reusing the old vector.
  for (let i = 0; i < allChunks.length; i += DB_BATCH_SIZE) {
    const batch = allChunks.slice(i, i + DB_BATCH_SIZE);
    const chunkRecords = batch.map(chunk => {
      const preserved = (chunk.chunk_type === "table" || chunk.chunk_type === "figure") && chunk.clause_number
        ? preserveDescribed?.get(chunk.clause_number)
        : undefined;
      return {
        standard_id,
        user_id: userId,
        organization_id: organizationId,
        clause_number: chunk.clause_number,
        clause_title: chunk.clause_title,
        content: preserved ?? chunk.content,
        page_number: chunk.page_number,
        chunk_index: chunk.chunk_index,
        chunk_type: chunk.chunk_type,
        is_normative: chunk.is_normative,
        embedding: null,
        is_indexed: preserved !== undefined,
      };
    });
    const { error: chunkError } = await supabaseAdmin.from("standard_chunks").insert(chunkRecords);
    if (chunkError) console.error(`Chunk insert error (batch ${i / DB_BATCH_SIZE}):`, chunkError);
    else console.log(`[${standard_id}] DB insert batch ${Math.floor(i / DB_BATCH_SIZE) + 1} done`);
  }

  console.log(`[${standard_id}] All chunks stored (text-only)`);

  // Chunks are in — safe to drop any OCR resume text now
  await supabaseAdmin.from("processing_jobs")
    .update({ ocr_text: null, ocr_next_page: null })
    .eq("standard_id", standard_id);

  // Update standard with chunk count — stays "processing" until embed-chunks
  // finishes. This is also the point new chunks are known to have been built
  // by `pipelineVersion` — stamped in the same write to avoid an extra one.
  await supabaseAdmin.from("standards").update({
    extraction_status: "processing",
    extraction_quality_score: qualityScore,
    is_partial: isPartial,
    total_chunks: totalChunks,
    indexed_chunks: 0,
    pipeline_version: pipelineVersion,
  }).eq("id", standard_id);
  await supabaseAdmin.from("processing_jobs")
    .update({ status: "processing", error_message: null, completed_at: null, heartbeat_at: new Date().toISOString() })
    .eq("standard_id", standard_id)
    .eq("status", "failed");

  // Hand off embedding to embed-chunks (runs in its own 150s window)
  const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const embedUrl = `${Deno.env.get("SUPABASE_URL")}/functions/v1/embed-chunks`;
  const embedTrigger = fetch(embedUrl, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${serviceRoleKey}`,
    },
    body: JSON.stringify({ standard_id, user_id: userId }),
  }).catch(e => console.error("Failed to trigger embed-chunks:", e));
  // waitUntil stops the runtime killing the instance before the request leaves
  (globalThis as any).EdgeRuntime?.waitUntil?.(embedTrigger);

  // Fire-and-forget: describe-figures generates AI descriptions for figure
  // chunks AND markdown transcriptions for table chunks — must fire for
  // either kind. It's a cheap no-op if everything is already described
  // (carried-forward content above is inserted with is_indexed = true, which
  // describe-figures' own fetch filters out).
  if (figureChunks.length > 0 || tableChunks.length > 0) {
    const describeUrl = `${Deno.env.get("SUPABASE_URL")}/functions/v1/describe-figures`;
    const describeTrigger = fetch(describeUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${serviceRoleKey}` },
      body: JSON.stringify({ standard_id, user_id: userId }),
    }).catch(e => console.error("Failed to trigger describe-figures:", e));
    (globalThis as any).EdgeRuntime?.waitUntil?.(describeTrigger);
  }

  return { totalChunks, tableChunkCount: tableChunks.length, figureChunkCount: figureChunks.length, isPartial };
}
